apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shortgg-frontend
  labels:
    app: shortgg-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shortgg-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: shortgg-frontend
    spec:
      containers:
      - image: shortgg/frontend-shortener:latest
        imagePullPolicy: Always
        name: frontend-shortener
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
